---

- name: Install openvpn packages
  apt: pkg=openvpn state=installed
  tags: openvpn-internal-client

- name: load tun device
  command: /usr/sbin/modprobe tun
  tags: openvpn-internal-client

- name: openvpn internal config
  template: src=client.conf.j2 dest=/etc/openvpn/internal.conf owner=root group=root
  tags: openvpn-internal-client
  notify:
    - restart openvpn

- name: install cert
  copy: src=internal.key dest=/etc/openvpn
  tags: openvpn-internal-client
