---

- hosts: all
  roles:
    - common
  vars:
    gpg_keyid: DEADFEED
    gpg_password: derpderpdummyvalue
    core_router: 10.1.0.1
    internal_server: mycorehost

- hosts: central
  roles:
    - openvpn-internal-server
  vars:
    core_router: 10.1.0.1
    internal_server: mycorehost

- hosts: leafnodes
  roles:
    - dnsmasq
    - openvpn-internal-server
    - openvpn-external
  vars:
    core_router: 10.1.0.1
    internal_server: mycorehost
