---
- name: install MySQL server
    action: apt name=mysql-server
    notify:
      - mysql_secure_installation

- name: Start the MySQL service
  service: name=mysql state=started enabled=true

- name: update mysql root password
  mysql_user: name=root host=localhost password={{ root_db_password }}

- name: copy .my.cnf file with root password credentials
  template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost
   - {{ inventory_hostname }}

- name: install redmine
  apt: pkg={{item}} state=installed
  with_items:
    - redmine
    - bundler
    - libapache2-mod-passenger
    - redmine-mysql

- name: Create Redmine directory link
  file: path=/var/www/redmine src=/usr/share/redmine/public state=link

- name: Set redmine permissions
  file: path=/usr/share/redmine/ recurse=yes owner=www-data group=www-data

- name: Install redmine apache config
  template: src=redmine.apache.j2 dest=/etc/apache2/sites-available/redmine.conf

- name: Make plugin assets directory
  file: path=/usr/share/plugin_assets state=directory owner=www-data group=www-data
- name: Create Redmine plugin assets link
  file: src=/var/cache/redmine/default/plugin_assets path=/usr/share/redmine/public/ state=link

- name: enable redmine site
  command: /usr/sbin/a2ensite redmine
  notify:
    - restart_apache


