---

- name: Install openvpn packages
  apt: pkg=openvpn state=installed
  tags: openvpn

- name: openvpn external config
  template: src=external.conf.j2 dest=/etc/openvpn/external.conf owner=root group=root
  notify:
    - restart openvpn
  tags: openvpn

- name: load tun device
  command: /usr/sbin/modprobe tun

- name: configure firewall, allow traffic on port 1194
  command: firewall-cmd --permanent --add-port=1194/tcp

- name: configure firewall, allow traffic on port 1194
  command: firewall-cmd --permanent --add-port=1194/udp

- name: add net access rule
  command: iptables -t nat -I POSTROUTING -s {{ external_net }}/24 -o eth0 -j MASQUERADE

- name: add access to other networks on the VPN
  command: route add -net {{ external_net }} netmask 255.255.255.0 gw {{ core_router }}

- name: install certs
  copy: src={{item}} dest=/etc/openvpn
  with_items:
    - {{ inventory_hostname }}.crt
    - {{ inventory_hostname }}.key
  tags: openvpn

# enable ip forwarding for net access
- sysctl: name=net.ipv4.ip_forward value=1 state=present
